name: Echo Only Workflow

on:
  push:
  pull_request:

jobs:
  echo-job:
    runs-on: ubuntu-latest
    name: deploy-to-prod
    steps:
      - name: Print message
        run: echo "âœ… GitHub Actions is working successfully!"
